### ISSUE TITLE
Artist links returning 404

### ISSUE THREAD

**Issue by jordishore** [jordishore/Discord-Odesli-Bot#7]
`2024-08-22 08:46:04,865 - INFO - https://open.spotify.com/artist/565hAYrcYB27cuhmezgJRb?si=JYY_gk8dR9qk7B2nLV08qg`

`2024-08-22 08:46:04,865 - INFO - Getting Songlink
2024-08-22 08:46:04,865 - INFO - https://api.song.link/v1-alpha.1/links?url=https://open.spotify.com/artist/565hAYrcYB27cuhmezgJRb?si=JYY_gk8dR9qk7B2nLV08qg&userCountry=AU`

`2024-08-22 08:46:05,176 - INFO - {'statusCode': 404, 'code': 'could_not_fetch_entity_data'}`

`2024-08-22 08:46:05 ERROR    discord.app_commands.tree Ignoring exception in command 'Get Universal Link'
Traceback (most recent call last):
  File "/home/container/modules/discord/app_commands/commands.py", line 1285, in _invoke
    await self._callback(interaction, arg)
  File "/home/container/bot.py", line 74, in get_link_from_message
    response = await SongLink().get_link(url=url_from_messaeg)
  File "/home/container/bot.py", line 42, in get_link
    songlink = str(data['pageUrl'])
KeyError: 'pageUrl'`

`The above exception was the direct cause of the following exception:`

`Traceback (most recent call last):
  File "/home/container/modules/discord/app_commands/tree.py", line 1190, in _call_context_menu
    await ctx_menu._invoke(interaction, value)
  File "/home/container/modules/discord/app_commands/commands.py", line 1289, in _invoke
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'Get Universal Link' raised an exception: KeyError: 'pageUrl'`

**Comment by jordishore** [comment]
Songlink API limitation. Only Song and Album are supported.
